# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdZNoOpZscZJOylIK7K42fxeKnUBVOSS
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('maxresdefault.jpg')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqorq)

from google.colab.patches import cv2_imshow
import cv2
ras=cv2.imread('wp9212784.jpg')
cv2_imshow(ras)

oqqora=cv2.cvtColor(ras,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
ra=cv2.imread('151286_81c9739f820ac7430f9d8f1ee008.jpg')
r=cv2.imread('bg-header2.jpg')
a=cv2.imread('model1.jpg')
cv2_imshow(ra)
cv2_imshow(r)
cv2_imshow(a)

oqqora=cv2.cvtColor(ra,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(r,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(a,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)